name: huapoai
description: "App huapo AI - Recomendaciones de moda con IA"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase - Backend
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  cloud_firestore: ^5.6.8
  firebase_storage: ^12.4.6

  # Autenticación
  google_sign_in: ^6.1.6

  # State Management
  provider: ^6.1.1

  # Navigation
  go_router: ^15.1.2

  # Cámara e imágenes
  camera: ^0.11.1
  image_picker: ^1.0.4

  # Utilidades
  cached_network_image: ^3.3.0
  uuid: ^4.2.1
  intl: ^0.20.2
  permission_handler: ^12.0.0+1
  shared_preferences: ^2.2.2

  # IA y análisis de imágenes
  tflite_flutter: ^0.11.0
  image: ^4.1.3

  # Compresión de imágenes
  flutter_image_compress: ^2.1.0

  # HTTP para APIs externas (Roboflow)
  http: ^1.1.0

  # UI
  animations: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/models/
    - assets/icons/
    - lib/data/models/